const Buttons = {
    DIRECTION_LEFT: 'DIRECTION_LEFT',
    DIRECTION_RIGHT: 'DIRECTION_RIGHT',
    DIRECTION_UP: 'DIRECTION_UP',
    DIRECTION_DOWN: 'DIRECTION_DOWN',
    LEFT_SHOULDER: 'LEFT_SHOULDER',
    LEFT_TRIGGER: 'LEFT_TRIGGER',
    RIGHT_SHOULDER: 'RIGHT_SHOULDER',
    RIGHT_TRIGGER: 'RIGHT_TRIGGER',
    FACE_1: 'FACE_1',
    FACE_2: 'FACE_2',
    FACE_3: 'FACE_3',
    FACE_4: 'FACE_4',
    START: 'START',
    SELECT: 'SELECT',
    STICK_CLICK_1: 'STICK_CLICK_1',
    STICK_CLICK_2: 'STICK_CLICK_2',
    HOME: 'HOME'
};

const Sticks = {
    STICK_1: 'STICK_1',
    STICK_2: 'STICK_2'
};

